### PR TITLE
gds-base 3.0.1

### PR DESCRIPTION
**Pull request by duncanmmacleod**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
This is blocked by https://git.ligo.org/gds/gds/-/issues/181.

**Comment by h-vetinari** [comment]
> This is blocked by https://git.ligo.org/gds/gds/-/issues/181.

This is not publicly visible - any updates?

**Comment by duncanmmacleod** [comment]
> > This is blocked by https://git.ligo.org/gds/gds/-/issues/181.
> 
> This is not publicly visible - any updates?

No, unfortunately not. I have pinged the package libraries on that ticket and am waiting for a reply.

**Comment by h-vetinari** [comment]
OK, thanks for checking. While we're waiting for that, would you mind if I make a small commit (or you do!) as follows?
```diff
  - name: gds-base-monitors
    script: install-base-monitors.sh
    build:
-      ignore_run_exports:
+      ignore_run_exports_from:
        # the build needs the c++ compiler, but doesn't
        # link against it
-       - libcxx  # [osx]
-       - libstdcxx-ng  # [linux]
+       - {{ compiler('cxx') }}
      run_exports:
        - {{ pin_subpackage("gds-base-monitors", max_pin="x") }}
    requirements:
```

**Comment by duncanmmacleod** [comment]
> OK, thanks for checking. While we're waiting for that, would you mind if I make a small commit (or you do!) as follows?
> 
> ```diff
>   - name: gds-base-monitors
>     script: install-base-monitors.sh
>     build:
> -      ignore_run_exports:
> +      ignore_run_exports_from:
>         # the build needs the c++ compiler, but doesn't
>         # link against it
> -       - libcxx  # [osx]
> -       - libstdcxx-ng  # [linux]
> +       - {{ compiler('cxx') }}
>       run_exports:
>         - {{ pin_subpackage("gds-base-monitors", max_pin="x") }}
>     requirements:
> ```

@h-vetinari, please carry on, I will review things as soon as I can get a patch from upstream.

**Pull request merged**
